### ISSUE TITLE
TypeError: Cannot read property 'craft' of undefined

### ISSUE THREAD

**Issue by saltymouse** [sanscheese/gridsome-source-craft-graphql#6]
After following the installation and setup outlined in the [readme](https://github.com/sanscheese/gridsome-source-craft-graphql#source-plugin):

```javascript
module.exports = {
  siteName: 'New Project',
  plugins: [{
    use: '@bhws/gridsome-source-craft-graphql',
    options: {
      url: 'https://cms.new-project.ddev.site/api',
      fieldName: 'craft',
      typeName: 'craft',
    }
  }]
}
```

 I then run `gridsome develop` I receive the following error:

```
TypeError: Cannot read property 'craft' of undefined
    at /Users/saltymouse/webdev/new-project/node_modules/@bhws/gridsome-source-craft-graphql/lib/templates-routes.js:22:35
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Plugins.run (/Users/saltymouse/webdev/new-project/node_modules/gridsome/lib/app/Plugins.js:141:11)
    at async Plugins.createPages (/Users/saltymouse/webdev/new-project/node_modules/gridsome/lib/app/Plugins.js:116:5)
```

However, if I use the generic `@gridsome/source-graphql` plugin:

```javascript
module.exports = {
  siteName: 'New Project',
  plugins: [{
    use: '@gridsome/source-graphql',
    options: {
      url: 'https://cms.new-project.ddev.site/api',
      fieldName: 'craft',
      typeName: 'craft',
    }
  }]
}
```

gridsome loads without error.

The GraphQL server is responding normally, too:
`curl -H "Content-Type: application/graphql" -d '{ping}' http://cms.new-project.ddev.site/api`
Response: `{"data":{"ping":"pong"}}`

Any ideas what could be causing this error? Looking forward to using this plugin!

- Craft CMS v3.4.17.1
- Gridsome v0.7.14

**Comment by denisbertrandbe** [comment]
Same problem here... any news ?

**Comment by sanscheese** [comment]
Hey, this issue seems to have slipped through. Have the entries been enabled in schema settings the craft GraphQL admin area?

Also, is the data visible in gridsome's GraphQL explorer?

**Comment by denisbertrandbe** [comment]
The GraphQL explorer is not available due to the error.
In the same time I don't see how to access a specific schema with a token (and provide authentification header).
So I have tried the same using public schema and have the following error : 

```
Initializing plugins...
Load sources - 0s
Create GraphQL schema - 0.36s
TypeError: Cannot read property 'entries' of undefined
    at /Users/denis/Sites/_stk/craft3_headless_gridsome/node_modules/@bhws/gridsome-source-craft-graphql/lib/live-preview.js:23:41
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Plugins.run (/Users/.../node_modules/gridsome/lib/app/Plugins.js:141:11)
    at async Plugins.createPages (/Users/denis/Sites/_stk/craft3_headless_gridsome/node_modules/gridsome/lib/app/Plugins.js:110:5)
```

On the craft side I have cleared GraphQL cache and add entries to the public schema...

**Comment by denisbertrandbe** [comment]
I forgot to revert a test config. Now it works with public schema. How can I specify a specific schema with auth header ? Thank you.

**Comment by sanscheese** [comment]
Add the headers in the plugin settings in gridsome.config.js:

```js
plugins: [
    {
      use: '@bhws/gridsome-source-craft-graphql',
      options: {
        url: 'https://example.com/api',
        headers: {
          Authorization: `Bearer ${process.env.AUTH_TOKEN}`,
        }
      }
    }
]
```

You can also enable the `livePreview` setting the config `livePreview: "dangerouslyAllowAuthorizationHeaders"`. As the config value is suggesting, be cautious with this, as it will then make these credentials available to the client code, which you may or may not be concerned about.

**Comment by bzkjyf** [comment]
Same problem:
TypeError: Cannot read property 'craft' of undefined

How to setup the craft GraphQL admin?
